/* ── Mock / Demo Data ── */

function calcWeightedScore(metrics) {
  const sv = { good: 100, warning: 50, poor: 0 };
  const impactWeight = { high: 3, medium: 1.5, foundational: 1 };
  let totalWeight = 0, totalScore = 0;
  metrics.forEach(m => {
    const base = impactWeight[m.impact] || 1;
    const w = m.weighted ? base * 1.25 : base;
    totalWeight += w;
    totalScore += w * (sv[m.status] ?? 0);
  });
  return Math.round(totalScore / totalWeight);
}

const webPerfMetrics = [
  { label: "Site Health", value: "68%", status: "poor", detail: "Measures crawlability, technical errors, and optimization issues. Best-in-class sites score 90%+.", weighted: true, impact: "high",
    why: "Site health directly influences how effectively search engines crawl and index your pages. A low score means critical pages may never appear in search results.",
    fix: "Run a full technical audit to identify and resolve broken links, redirect chains, and crawl errors systematically.",
    expectedImpact: "Improving site health to 90%+ can increase indexed pages by 15-25% and improve crawl efficiency.",
    difficulty: "Medium" },
  { label: "Page Speed & Performance", value: "62%", status: "poor", detail: "Evaluates load speed, performance efficiency, and user experience impact. Target: 90%+.", impact: "high",
    why: "Page speed is a confirmed Google ranking factor. Slow sites lose visitors — 53% of mobile users abandon pages that take over 3 seconds to load.",
    fix: "Compress images, implement lazy loading, enable browser caching, and defer non-critical JavaScript.",
    expectedImpact: "Reaching 90%+ performance can reduce bounce rates by 20-30% and improve conversion rates.",
    difficulty: "Medium" },
  { label: "Mobile Optimization", value: "Yes", status: "good", detail: "Confirms your site is optimized for mobile users and Google's mobile-first indexing.", impact: "foundational",
    why: "Google uses mobile-first indexing — your mobile site IS your site for ranking purposes.",
    fix: "No action needed. Continue testing across devices when making site changes.",
    expectedImpact: "Maintains eligibility for mobile search rankings, which represent 60%+ of all searches.",
    difficulty: "N/A" },
  { label: "Security & SSL", value: "Valid", status: "good", detail: "Status ensures encrypted data protection and trust signals for users and search engines.", impact: "foundational",
    why: "SSL is a ranking signal and browsers flag non-secure sites with warnings, reducing visitor trust.",
    fix: "No action needed. Ensure certificate auto-renews before expiration.",
    expectedImpact: "Maintains trust signals and prevents browser security warnings.",
    difficulty: "N/A" },
  { label: "HTTP/2 Support", value: "Enabled", status: "good", detail: "Improves load performance through faster resource delivery.", impact: "foundational",
    why: "HTTP/2 enables multiplexed connections, reducing page load times significantly over HTTP/1.1.",
    fix: "No action needed. HTTP/2 is properly configured.",
    expectedImpact: "Supports faster page delivery — particularly beneficial for resource-heavy pages.",
    difficulty: "N/A" },
  { label: "Image Optimization", value: "34% Improvement Needed", status: "poor", detail: "17 of 50 images are slowing down load time. Slower pages reduce conversions and search performance.", impact: "high",
    why: "Unoptimized images are the #1 cause of slow page loads. They increase bandwidth costs and hurt Core Web Vitals scores.",
    fix: "Convert images to WebP format, implement responsive srcset attributes, and compress all images above 100KB.",
    expectedImpact: "Can reduce page load time by 40-60% on image-heavy pages.",
    difficulty: "Low" },
  { label: "Alt Tags", value: "58% Incomplete", status: "poor", detail: "Missing alt text limits accessibility and weakens image search visibility.", impact: "medium",
    why: "Alt tags enable image search rankings and are required for accessibility compliance (ADA/WCAG).",
    fix: "Audit all images and add descriptive, keyword-relevant alt text to each one.",
    expectedImpact: "Can open new traffic channels through Google Image Search and improve accessibility compliance.",
    difficulty: "Low" },
];
export const mockWebPerf = {
  score: calcWeightedScore(webPerfMetrics),
  metrics: webPerfMetrics,
};

export const mockSEO = {
  score: 65,
  metrics: [
    { label: "Organic Keywords", value: "312", status: "warning", detail: "312 keywords currently ranking in search results. Expanding keyword coverage increases visibility and traffic opportunities.", impact: "high",
      why: "Keyword rankings determine how often your site appears in search results. More rankings = more potential traffic.",
      fix: "Conduct keyword gap analysis to identify high-value terms competitors rank for that you don't.",
      expectedImpact: "Expanding from 312 to 500+ keywords could increase organic traffic by 30-50%.",
      difficulty: "Medium" },
    { label: "Branded Traffic Share", value: "24%", status: "poor", detail: "24% of organic traffic comes from branded searches. Low branded traffic may indicate limited brand awareness or weak demand capture.", impact: "high",
      why: "Low branded search volume means fewer people are actively looking for your company — a sign of weak brand awareness.",
      fix: "Invest in brand visibility campaigns, PR mentions, and thought leadership content to drive branded search demand.",
      expectedImpact: "Increasing branded traffic to 40%+ signals stronger brand recognition and higher conversion potential.",
      difficulty: "High" },
    { label: "Indexation Efficiency", value: "77%", status: "warning", detail: "156 of 203 pages are indexed. Unindexed pages cannot rank in search results, limiting organic growth.", impact: "high",
      why: "If Google hasn't indexed a page, it cannot appear in search results — those pages generate zero organic traffic.",
      fix: "Review unindexed pages for thin content, crawl blocks, or noindex tags. Submit priority pages via Search Console.",
      expectedImpact: "Indexing all quality pages could unlock rankings for 47 additional pages.",
      difficulty: "Low" },
    { label: "Domain Authority Score", value: "32/100", status: "warning", detail: "Indicates current backlink strength and competitive positioning. Higher authority improves ranking potential across competitive keywords.", impact: "medium",
      why: "Domain authority reflects your site's competitive strength. Higher authority means easier rankings for competitive terms.",
      fix: "Build high-quality backlinks through guest posts, digital PR, and industry partnerships.",
      expectedImpact: "Reaching DA 45+ would significantly improve ranking potential for mid-difficulty keywords.",
      difficulty: "High" },
    { label: "Backlink Profile", value: "423", status: "warning", detail: "423 referring links supporting your domain. Quality and relevance matter more than volume.", impact: "medium",
      why: "Backlinks remain one of the strongest ranking signals. Quality links from relevant sites pass authority to your domain.",
      fix: "Disavow toxic links and pursue link-building campaigns targeting industry-relevant, high-authority domains.",
      expectedImpact: "Improving link quality can lift rankings for mid-to-high difficulty keywords.",
      difficulty: "High" },
    { label: "XML Sitemap Status", value: "Found", status: "good", detail: "Sitemap detected and accessible to search engines.", impact: "foundational",
      why: "A sitemap helps search engines discover and understand the structure of your site.",
      fix: "No action needed. Ensure sitemap stays updated as new pages are added.",
      expectedImpact: "Maintains efficient crawl discovery for new and updated content.",
      difficulty: "N/A" },
    { label: "Robots.txt Configuration", value: "Yes", status: "good", detail: "Crawl directives are properly structured.", impact: "foundational",
      why: "Robots.txt controls which pages search engines can access — misconfiguration can block important content.",
      fix: "No action needed. Crawl directives are properly structured.",
      expectedImpact: "Ensures search engines can access all important pages without restriction.",
      difficulty: "N/A" },
  ],
};

/*
 * Content Performance scoring:
 *   - First 2 metrics (Blog Exists, Content Freshness) are weighted 1.25x
 *   - Remaining metrics are weighted 1.0x
 *   - Status values: good = 100, warning = 50, poor = 0
 *   - Score = weighted avg of all metric scores
 */
const contentMetrics = [
  { label: "Blog Page Exists", value: "Yes", status: "good", detail: "A dedicated blog/news page was detected", weighted: true, impact: "foundational",
    why: "A blog page is the foundation for content marketing — it's where fresh, indexable content lives.", fix: "No action needed.", expectedImpact: "Provides the infrastructure for ongoing content strategy.", difficulty: "N/A" },
  { label: "Content Freshness", value: "38 days avg", status: "warning", detail: "Last blog post: 52 days ago", weighted: true, impact: "high",
    why: "Search engines favor sites that publish fresh content regularly. Stale content signals an inactive or abandoned site.",
    fix: "Establish a minimum 2x/month publishing cadence with keyword-targeted blog posts.",
    expectedImpact: "Regular publishing can increase organic traffic by 20-40% within 6 months.", difficulty: "Medium" },
  { label: "Meta Descriptions", value: "68% optimized", status: "warning", detail: "32% of pages missing or have duplicate meta descriptions", impact: "high",
    why: "Meta descriptions control how your pages appear in search results. Missing or duplicate descriptions reduce click-through rates.",
    fix: "Write unique, compelling meta descriptions for all pages — prioritize high-traffic pages first.",
    expectedImpact: "Optimized descriptions can improve CTR by 5-10%, driving more traffic from existing rankings.", difficulty: "Low" },
  { label: "H1 Tags", value: "All pages have H1", status: "good", detail: "Every page has a unique H1 heading tag", impact: "foundational",
    why: "H1 tags tell search engines the primary topic of each page.", fix: "No action needed.", expectedImpact: "Maintains clear page topic signals for search engines.", difficulty: "N/A" },
  { label: "Avg. Time on Page", value: "1m 42s", status: "warning", detail: "Industry avg is 2m 30s", impact: "medium",
    why: "Low time on page suggests content isn't engaging visitors — a signal to search engines that your content may not satisfy search intent.",
    fix: "Improve content depth, add visuals, and use better formatting to increase engagement.",
    expectedImpact: "Reaching 2m+ avg can improve engagement signals and support better rankings.", difficulty: "Medium" },
  { label: "Bounce Rate", value: "64%", status: "poor", detail: "Above the 50% threshold", impact: "high",
    why: "A high bounce rate means visitors leave without interacting — indicating content or UX issues.",
    fix: "Improve page load speed, strengthen above-the-fold content, and add clear calls to action.",
    expectedImpact: "Reducing bounce rate below 50% can significantly improve conversion rates.", difficulty: "Medium" },
  { label: "Readability Score", value: "Grade 11", status: "warning", detail: "Aim for Grade 8 for broader reach", impact: "medium",
    why: "Complex content limits your audience. Most web content should target an 8th-grade reading level for maximum reach.",
    fix: "Simplify sentence structure, use shorter paragraphs, and replace jargon with plain language.",
    expectedImpact: "Broader accessibility can increase engagement and reduce bounce rates.", difficulty: "Low" },
  { label: "Word Count (top pages)", value: "~620 avg", status: "poor", detail: "Competitors average 1,400+ words", impact: "high",
    why: "Thin content struggles to rank for competitive keywords. Longer, comprehensive content demonstrates topical authority.",
    fix: "Expand top landing pages to 1,200+ words with in-depth, valuable information.",
    expectedImpact: "Pages with 1,200+ words rank significantly higher for competitive terms.", difficulty: "Medium" },
  { label: "Internal Links / Page", value: "2.1 avg", status: "poor", detail: "Best practice is 3+ per page", impact: "medium",
    why: "Internal links distribute page authority and help search engines discover content. Too few = wasted link equity.",
    fix: "Add 3-5 contextual internal links per page, prioritizing links to high-value pages.",
    expectedImpact: "Better internal linking can improve crawl depth and boost rankings for linked pages.", difficulty: "Low" },
  { label: "Content-to-Code Ratio", value: "18%", status: "warning", detail: "Aim for 25%+", impact: "medium",
    why: "A low content-to-code ratio means your pages have more HTML/scripts than actual content — search engines prefer content-rich pages.",
    fix: "Reduce unnecessary scripts, clean up HTML bloat, and add more substantive content.",
    expectedImpact: "Improving ratio to 25%+ signals content-rich pages to search engines.", difficulty: "Medium" },
  { label: "Duplicate Content", value: "3 pages flagged", status: "poor", detail: "Near-duplicate meta descriptions", impact: "high",
    why: "Duplicate content confuses search engines about which page to rank, diluting your ranking potential.",
    fix: "Write unique content and meta descriptions for each flagged page. Add canonical tags where appropriate.",
    expectedImpact: "Resolving duplicates allows search engines to properly index and rank each unique page.", difficulty: "Low" },
];
export const mockContentPerf = {
  score: calcWeightedScore(contentMetrics),
  metrics: contentMetrics,
};

export const mockSocialLocal = {
  socialScore: 45,
  localScore: 70,
  combinedScore: 55,
  platforms: [
    { name: "LinkedIn", status: "Active", followers: "890", activity: "4 posts / month", health: "good" },
    { name: "Google Business", status: "Claimed", followers: "—", activity: "Last post 12 days ago", health: "warning" },
    { name: "Facebook", status: "Active", followers: "2,340", activity: "3 posts / month", health: "warning" },
    { name: "Instagram", status: "Active", followers: "1,120", activity: "2 posts / month", health: "poor" },
    { name: "X (Twitter)", status: "Inactive", followers: "312", activity: "No posts in 60+ days", health: "poor" },
    { name: "YouTube", status: "Not Found", followers: "—", activity: "—", health: "poor" },
    { name: "TikTok", status: "Not Found", followers: "—", activity: "—", health: "poor" },
  ],
  signals: [
    { label: "Open Graph Tags", value: "Partial", status: "warning", detail: "Missing og:image on 8 pages", impact: "medium",
      why: "Open Graph tags control how your pages appear when shared on social media. Missing tags = generic, unappealing previews.",
      fix: "Add og:title, og:description, and og:image tags to all pages — prioritize high-traffic pages.",
      expectedImpact: "Rich social previews can increase click-through rates from social shares by 2-3x.", difficulty: "Low" },
    { label: "Twitter Cards", value: "Incomplete", status: "poor", detail: "No twitter:card meta tags found", impact: "medium",
      why: "Twitter Cards create rich media previews when links are shared on X — without them, shared links appear as plain text.",
      fix: "Add twitter:card, twitter:title, twitter:description, and twitter:image meta tags to all pages.",
      expectedImpact: "Enables rich previews on X, improving engagement with shared content.", difficulty: "Low" },
    { label: "Social Share Buttons", value: "None", status: "poor", detail: "No sharing widgets detected", impact: "medium",
      why: "Without share buttons, visitors have no easy way to spread your content — reducing organic amplification.",
      fix: "Add floating or inline social share buttons to blog posts and key landing pages.",
      expectedImpact: "Pages with share buttons receive 7x more social engagement on average.", difficulty: "Low" },
    { label: "Brand Consistency", value: "Mixed", status: "warning", detail: "Profile images differ across platforms", impact: "high",
      why: "Inconsistent branding across platforms confuses customers and weakens brand recognition and trust.",
      fix: "Standardize profile images, bios, and brand messaging across all social platforms.",
      expectedImpact: "Consistent branding increases revenue by up to 23% according to brand studies.", difficulty: "Low" },
  ],
  localMetrics: [
    { label: "GBP Listing", value: "Claimed & Verified", status: "good", cta: "Passing" },
    { label: "Reviews", value: "4.2★ (89 reviews)", status: "good", cta: "Passing" },
    { label: "Local Citations", value: "34 found", status: "warning", cta: "Build Citations" },
    { label: "Local Keywords", value: "Moderate Usage", status: "warning", cta: "Expand Keywords" },
    { label: "Service Area", value: "Defined", status: "good", cta: "Passing" },
    { label: "Local Schema", value: "Present", status: "good", cta: "Passing" },
    { label: "Apple Maps", value: "Listed", status: "good", cta: "Passing" },
    { label: "Bing Places", value: "Incomplete", status: "poor", cta: "Claim Listing" },
  ],
  reviews: [
    { author: "Sarah M.", rating: 5, timeAgo: "2 weeks ago", text: "Excellent service, very professional team." },
    { author: "James K.", rating: 4, timeAgo: "1 month ago", text: "Good results, communication could be better." },
    { author: "Lisa R.", rating: 5, timeAgo: "2 months ago", text: "Transformed our online presence completely." },
  ],
};

export const mockAISEO = {
  score: 41,
  metrics: [
    { label: "AI Search Mentions", value: "2 engines", status: "poor", impact: "high",
      why: "AI search engines like ChatGPT and Perplexity are becoming primary discovery channels. Low mentions = invisible to AI users.",
      fix: "Create comprehensive, well-structured content that AI models can easily cite and reference.",
      expectedImpact: "Being cited in AI search results can drive significant referral traffic from a growing channel.", difficulty: "High" },
    { label: "Structured Data", value: "Partial", status: "warning", impact: "high",
      why: "Structured data helps search engines and AI systems understand your content at a deeper level.",
      fix: "Implement Organization, FAQ, Service, and LocalBusiness schema across relevant pages.",
      expectedImpact: "Full structured data can enable rich results and improve AI content understanding.", difficulty: "Medium" },
    { label: "Entity Recognition", value: "Low", status: "poor", impact: "high",
      why: "If search engines don't recognize your brand as a distinct entity, you lose control over branded search results.",
      fix: "Build entity signals through consistent NAP data, schema markup, Wikidata entries, and authoritative mentions.",
      expectedImpact: "Strong entity recognition enables Knowledge Panels and branded search control.", difficulty: "High" },
    { label: "Content Depth", value: "Below Average", status: "poor", impact: "medium",
      why: "Shallow content is unlikely to be cited by AI systems or rank for competitive keywords.",
      fix: "Expand key pages with comprehensive, expert-level content that covers topics thoroughly.",
      expectedImpact: "Deeper content increases citation likelihood and topical authority signals.", difficulty: "Medium" },
    { label: "FAQ Schema", value: "Incomplete", status: "poor", impact: "medium",
      why: "FAQ schema enables rich results in Google and provides structured Q&A content that AI systems can directly cite.",
      fix: "Add FAQ schema to service pages, product pages, and any page addressing common customer questions.",
      expectedImpact: "FAQ rich results can increase page real estate in SERPs by up to 50%.", difficulty: "Low" },
    { label: "Topical Authority", value: "Moderate", status: "warning", impact: "high",
      why: "Topical authority signals to search engines that you're an expert in your field — critical for ranking and AI citations.",
      fix: "Build content clusters around core topics with pillar pages and supporting articles.",
      expectedImpact: "Strong topical authority can improve rankings across entire content clusters.", difficulty: "High" },
    { label: "Citation Likelihood", value: "18%", status: "poor", impact: "high",
      why: "Low citation likelihood means AI search tools are unlikely to reference your content when answering user queries.",
      fix: "Create definitive, data-rich content that serves as a primary source on key topics.",
      expectedImpact: "Increasing citation likelihood opens a growing traffic channel as AI search adoption rises.", difficulty: "High" },
    { label: "Knowledge Panel", value: "Incomplete", status: "poor", impact: "high",
      why: "A Knowledge Panel establishes brand authority and occupies premium real estate in Google search results.",
      fix: "Strengthen entity signals through Wikidata, consistent schema, authoritative mentions, and verified profiles.",
      expectedImpact: "A Knowledge Panel increases brand trust and click-through rates on branded searches.", difficulty: "High" },
  ],
};

export const mockEntity = {
  score: 53,
  metrics: [
    { label: "NAP Consistency", value: "4 mismatches", status: "poor", detail: "4 inconsistencies found across directories. Inconsistent name, address, or phone data can reduce local ranking trust signals.", impact: "high",
      why: "Inconsistent business information across directories confuses search engines and erodes trust in your local listings.",
      fix: "Audit and correct all business listings to ensure identical Name, Address, and Phone across every directory.",
      expectedImpact: "Consistent NAP data is a top-3 local ranking factor — fixing this can immediately boost local visibility.", difficulty: "Low" },
    { label: "Verified Google Business Profile", value: "Yes", status: "good", detail: "A verified profile is essential for local map pack visibility and customer trust.", impact: "foundational",
      why: "A verified GBP is required to appear in Google's local map pack — the highest-converting local search placement.",
      fix: "No action needed. Keep profile updated with current hours, photos, and posts.", expectedImpact: "Maintains eligibility for local map pack and Google Maps visibility.", difficulty: "N/A" },
    { label: "Google Reviews", value: "89 reviews", status: "good", detail: "Strong review volume improves local rankings and conversion trust.", impact: "foundational",
      why: "Review quantity and quality are direct local ranking factors and strongly influence customer purchase decisions.",
      fix: "No action needed. Continue encouraging reviews and responding to all feedback.", expectedImpact: "Ongoing review growth sustains local ranking strength and conversion trust.", difficulty: "N/A" },
    { label: "Schema Markup", value: "Organization only", status: "warning", detail: "Additional structured data types could improve local and entity visibility.", impact: "high",
      why: "Limited schema means search engines have an incomplete understanding of your business, services, and relationships.",
      fix: "Add LocalBusiness, Service, FAQ, and Review schema to relevant pages.",
      expectedImpact: "Comprehensive schema enables rich results and improves entity recognition.", difficulty: "Medium" },
    { label: "Knowledge Graph", value: "Incomplete", status: "poor", detail: "A Knowledge Panel increases brand authority and search control.", impact: "high",
      why: "Without a Knowledge Panel, you have limited control over how your brand appears in search results.",
      fix: "Build entity signals through Wikidata, consistent schema, and authoritative third-party mentions.",
      expectedImpact: "A Knowledge Panel establishes brand authority and increases branded search CTR.", difficulty: "High" },
    { label: "Entity Associations", value: "Weak", status: "poor", detail: "Stronger entity connections improve AI and semantic search visibility.", impact: "high",
      why: "Weak entity associations mean search engines and AI systems don't understand your brand's relationships and relevance.",
      fix: "Build same-as links, earn mentions on authoritative sites, and strengthen Wikidata relationships.",
      expectedImpact: "Stronger entity signals improve visibility in both traditional and AI-powered search.", difficulty: "High" },
    { label: "Brand SERP Control", value: "Improvement Needed", status: "warning", detail: "Limited control over branded search results can impact credibility.", impact: "high",
      why: "When someone searches your brand name, you should control the majority of page-one results. Gaps let competitors or negative content fill the space.",
      fix: "Optimize owned properties (social profiles, directories, PR) to dominate branded search results.",
      expectedImpact: "Full brand SERP control protects reputation and increases click-through to owned properties.", difficulty: "Medium" },
    { label: "Wikidata", value: "Incomplete", status: "poor", detail: "Wikidata strengthens knowledge graph recognition and entity authority.", impact: "medium",
      why: "Wikidata is a primary data source for Google's Knowledge Graph. Without an entry, you're invisible to this system.",
      fix: "Create a Wikidata entry with accurate business information and link to authoritative sources.",
      expectedImpact: "A Wikidata entry can trigger Knowledge Panel eligibility and strengthen entity authority.", difficulty: "Medium" },
    { label: "Same-As Links", value: "2 found", status: "warning", detail: "Cross-platform identity links help search engines verify entity ownership.", impact: "medium",
      why: "Same-as links in schema connect your website to your social profiles, confirming entity ownership across the web.",
      fix: "Add sameAs schema properties linking to all verified social profiles and directory listings.",
      expectedImpact: "Strengthens entity verification and supports Knowledge Panel generation.", difficulty: "Low" },
    { label: "Entity Descriptions", value: "Inconsistent", status: "warning", detail: "Consistent messaging strengthens entity clarity for search engines and AI systems.", impact: "medium",
      why: "Different descriptions across platforms confuse search engines about what your business actually does.",
      fix: "Standardize your business description across all platforms, directories, and social profiles.",
      expectedImpact: "Consistent messaging strengthens entity clarity and improves brand search relevance.", difficulty: "Low" },
  ],
};
